/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TeamRouteImport } from './routes/team'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as GetInvolvedIndexRouteImport } from './routes/get-involved.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as GetInvolvedVolunteerInfoRouteImport } from './routes/get-involved.volunteer-info'
import { Route as GetInvolvedVolunteerRouteImport } from './routes/get-involved.volunteer'
import { Route as GetInvolvedCsrInfoRouteImport } from './routes/get-involved.csr-info'
import { Route as GetInvolvedCsrRouteImport } from './routes/get-involved.csr'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminWeeklyHighlightsRouteImport } from './routes/admin.weekly-highlights'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as AdminVolunteerPageRouteImport } from './routes/admin.volunteer-page'
import { Route as AdminVoicesRouteImport } from './routes/admin.voices'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsManagerRouteImport } from './routes/admin.testimonials-manager'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminNewsBannerRouteImport } from './routes/admin.news-banner'
import { Route as AdminMilestonesRouteImport } from './routes/admin.milestones'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImagesRouteImport } from './routes/admin.images'
import { Route as AdminHeroCarouselRouteImport } from './routes/admin.hero-carousel'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminCsrPageRouteImport } from './routes/admin.csr-page'
import { Route as AdminCsrRouteImport } from './routes/admin.csr'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as TeamTypeIdRouteImport } from './routes/team.$type.$id'
import { Route as AboutTrusteeSlugRouteImport } from './routes/about.trustee.$slug'
import { Route as AboutAdvisorySlugRouteImport } from './routes/about.advisory.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedIndexRoute = GetInvolvedIndexRouteImport.update({
  id: '/get-involved/',
  path: '/get-involved/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedVolunteerInfoRoute =
  GetInvolvedVolunteerInfoRouteImport.update({
    id: '/get-involved/volunteer-info',
    path: '/get-involved/volunteer-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const GetInvolvedVolunteerRoute = GetInvolvedVolunteerRouteImport.update({
  id: '/get-involved/volunteer',
  path: '/get-involved/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedCsrInfoRoute = GetInvolvedCsrInfoRouteImport.update({
  id: '/get-involved/csr-info',
  path: '/get-involved/csr-info',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedCsrRoute = GetInvolvedCsrRouteImport.update({
  id: '/get-involved/csr',
  path: '/get-involved/csr',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWeeklyHighlightsRoute = AdminWeeklyHighlightsRouteImport.update({
  id: '/weekly-highlights',
  path: '/weekly-highlights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteerPageRoute = AdminVolunteerPageRouteImport.update({
  id: '/volunteer-page',
  path: '/volunteer-page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoicesRoute = AdminVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsManagerRoute =
  AdminTestimonialsManagerRouteImport.update({
    id: '/testimonials-manager',
    path: '/testimonials-manager',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsBannerRoute = AdminNewsBannerRouteImport.update({
  id: '/news-banner',
  path: '/news-banner',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMilestonesRoute = AdminMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroCarouselRoute = AdminHeroCarouselRouteImport.update({
  id: '/hero-carousel',
  path: '/hero-carousel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCsrPageRoute = AdminCsrPageRouteImport.update({
  id: '/csr-page',
  path: '/csr-page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCsrRoute = AdminCsrRouteImport.update({
  id: '/csr',
  path: '/csr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const TeamTypeIdRoute = TeamTypeIdRouteImport.update({
  id: '/$type/$id',
  path: '/$type/$id',
  getParentRoute: () => TeamRoute,
} as any)
const AboutTrusteeSlugRoute = AboutTrusteeSlugRouteImport.update({
  id: '/trustee/$slug',
  path: '/trustee/$slug',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAdvisorySlugRoute = AboutAdvisorySlugRouteImport.update({
  id: '/advisory/$slug',
  path: '/advisory/$slug',
  getParentRoute: () => AboutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/milestones': typeof MilestonesRoute
  '/team': typeof TeamRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/csr': typeof AdminCsrRoute
  '/admin/csr-page': typeof AdminCsrPageRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero-carousel': typeof AdminHeroCarouselRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/admin/news-banner': typeof AdminNewsBannerRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/testimonials-manager': typeof AdminTestimonialsManagerRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voices': typeof AdminVoicesRoute
  '/admin/volunteer-page': typeof AdminVolunteerPageRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/weekly-highlights': typeof AdminWeeklyHighlightsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/get-involved/csr': typeof GetInvolvedCsrRoute
  '/get-involved/csr-info': typeof GetInvolvedCsrInfoRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/get-involved/volunteer-info': typeof GetInvolvedVolunteerInfoRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/about/advisory/$slug': typeof AboutAdvisorySlugRoute
  '/about/trustee/$slug': typeof AboutTrusteeSlugRoute
  '/team/$type/$id': typeof TeamTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/milestones': typeof MilestonesRoute
  '/team': typeof TeamRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/csr': typeof AdminCsrRoute
  '/admin/csr-page': typeof AdminCsrPageRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero-carousel': typeof AdminHeroCarouselRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/admin/news-banner': typeof AdminNewsBannerRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/testimonials-manager': typeof AdminTestimonialsManagerRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voices': typeof AdminVoicesRoute
  '/admin/volunteer-page': typeof AdminVolunteerPageRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/weekly-highlights': typeof AdminWeeklyHighlightsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/get-involved/csr': typeof GetInvolvedCsrRoute
  '/get-involved/csr-info': typeof GetInvolvedCsrInfoRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/get-involved/volunteer-info': typeof GetInvolvedVolunteerInfoRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/get-involved': typeof GetInvolvedIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/about/advisory/$slug': typeof AboutAdvisorySlugRoute
  '/about/trustee/$slug': typeof AboutTrusteeSlugRoute
  '/team/$type/$id': typeof TeamTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/milestones': typeof MilestonesRoute
  '/team': typeof TeamRouteWithChildren
  '/testimonials': typeof TestimonialsRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/csr': typeof AdminCsrRoute
  '/admin/csr-page': typeof AdminCsrPageRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/hero-carousel': typeof AdminHeroCarouselRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/admin/news-banner': typeof AdminNewsBannerRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/testimonials-manager': typeof AdminTestimonialsManagerRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/voices': typeof AdminVoicesRoute
  '/admin/volunteer-page': typeof AdminVolunteerPageRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/admin/weekly-highlights': typeof AdminWeeklyHighlightsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/get-involved/csr': typeof GetInvolvedCsrRoute
  '/get-involved/csr-info': typeof GetInvolvedCsrInfoRoute
  '/get-involved/volunteer': typeof GetInvolvedVolunteerRoute
  '/get-involved/volunteer-info': typeof GetInvolvedVolunteerInfoRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/get-involved/': typeof GetInvolvedIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/about/advisory/$slug': typeof AboutAdvisorySlugRoute
  '/about/trustee/$slug': typeof AboutTrusteeSlugRoute
  '/team/$type/$id': typeof TeamTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/donate'
    | '/gallery'
    | '/milestones'
    | '/team'
    | '/testimonials'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/contacts'
    | '/admin/csr'
    | '/admin/csr-page'
    | '/admin/donations'
    | '/admin/gallery'
    | '/admin/hero-carousel'
    | '/admin/images'
    | '/admin/login'
    | '/admin/milestones'
    | '/admin/news-banner'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/testimonials-manager'
    | '/admin/users'
    | '/admin/voices'
    | '/admin/volunteer-page'
    | '/admin/volunteers'
    | '/admin/weekly-highlights'
    | '/blog/$slug'
    | '/get-involved/csr'
    | '/get-involved/csr-info'
    | '/get-involved/volunteer'
    | '/get-involved/volunteer-info'
    | '/programs/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/get-involved/'
    | '/programs/'
    | '/projects/'
    | '/about/advisory/$slug'
    | '/about/trustee/$slug'
    | '/team/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/gallery'
    | '/milestones'
    | '/team'
    | '/testimonials'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/contacts'
    | '/admin/csr'
    | '/admin/csr-page'
    | '/admin/donations'
    | '/admin/gallery'
    | '/admin/hero-carousel'
    | '/admin/images'
    | '/admin/login'
    | '/admin/milestones'
    | '/admin/news-banner'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/testimonials-manager'
    | '/admin/users'
    | '/admin/voices'
    | '/admin/volunteer-page'
    | '/admin/volunteers'
    | '/admin/weekly-highlights'
    | '/blog/$slug'
    | '/get-involved/csr'
    | '/get-involved/csr-info'
    | '/get-involved/volunteer'
    | '/get-involved/volunteer-info'
    | '/programs/$slug'
    | '/projects/$slug'
    | '/admin'
    | '/blog'
    | '/get-involved'
    | '/programs'
    | '/projects'
    | '/about/advisory/$slug'
    | '/about/trustee/$slug'
    | '/team/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/donate'
    | '/gallery'
    | '/milestones'
    | '/team'
    | '/testimonials'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/contacts'
    | '/admin/csr'
    | '/admin/csr-page'
    | '/admin/donations'
    | '/admin/gallery'
    | '/admin/hero-carousel'
    | '/admin/images'
    | '/admin/login'
    | '/admin/milestones'
    | '/admin/news-banner'
    | '/admin/programs'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/testimonials-manager'
    | '/admin/users'
    | '/admin/voices'
    | '/admin/volunteer-page'
    | '/admin/volunteers'
    | '/admin/weekly-highlights'
    | '/blog/$slug'
    | '/get-involved/csr'
    | '/get-involved/csr-info'
    | '/get-involved/volunteer'
    | '/get-involved/volunteer-info'
    | '/programs/$slug'
    | '/projects/$slug'
    | '/admin/'
    | '/blog/'
    | '/get-involved/'
    | '/programs/'
    | '/projects/'
    | '/about/advisory/$slug'
    | '/about/trustee/$slug'
    | '/team/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  MilestonesRoute: typeof MilestonesRoute
  TeamRoute: typeof TeamRouteWithChildren
  TestimonialsRoute: typeof TestimonialsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GetInvolvedCsrRoute: typeof GetInvolvedCsrRoute
  GetInvolvedCsrInfoRoute: typeof GetInvolvedCsrInfoRoute
  GetInvolvedVolunteerRoute: typeof GetInvolvedVolunteerRoute
  GetInvolvedVolunteerInfoRoute: typeof GetInvolvedVolunteerInfoRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GetInvolvedIndexRoute: typeof GetInvolvedIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/': {
      id: '/get-involved/'
      path: '/get-involved'
      fullPath: '/get-involved/'
      preLoaderRoute: typeof GetInvolvedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/volunteer-info': {
      id: '/get-involved/volunteer-info'
      path: '/get-involved/volunteer-info'
      fullPath: '/get-involved/volunteer-info'
      preLoaderRoute: typeof GetInvolvedVolunteerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/volunteer': {
      id: '/get-involved/volunteer'
      path: '/get-involved/volunteer'
      fullPath: '/get-involved/volunteer'
      preLoaderRoute: typeof GetInvolvedVolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/csr-info': {
      id: '/get-involved/csr-info'
      path: '/get-involved/csr-info'
      fullPath: '/get-involved/csr-info'
      preLoaderRoute: typeof GetInvolvedCsrInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved/csr': {
      id: '/get-involved/csr'
      path: '/get-involved/csr'
      fullPath: '/get-involved/csr'
      preLoaderRoute: typeof GetInvolvedCsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/weekly-highlights': {
      id: '/admin/weekly-highlights'
      path: '/weekly-highlights'
      fullPath: '/admin/weekly-highlights'
      preLoaderRoute: typeof AdminWeeklyHighlightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteer-page': {
      id: '/admin/volunteer-page'
      path: '/volunteer-page'
      fullPath: '/admin/volunteer-page'
      preLoaderRoute: typeof AdminVolunteerPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voices': {
      id: '/admin/voices'
      path: '/voices'
      fullPath: '/admin/voices'
      preLoaderRoute: typeof AdminVoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials-manager': {
      id: '/admin/testimonials-manager'
      path: '/testimonials-manager'
      fullPath: '/admin/testimonials-manager'
      preLoaderRoute: typeof AdminTestimonialsManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news-banner': {
      id: '/admin/news-banner'
      path: '/news-banner'
      fullPath: '/admin/news-banner'
      preLoaderRoute: typeof AdminNewsBannerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/milestones': {
      id: '/admin/milestones'
      path: '/milestones'
      fullPath: '/admin/milestones'
      preLoaderRoute: typeof AdminMilestonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero-carousel': {
      id: '/admin/hero-carousel'
      path: '/hero-carousel'
      fullPath: '/admin/hero-carousel'
      preLoaderRoute: typeof AdminHeroCarouselRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/csr-page': {
      id: '/admin/csr-page'
      path: '/csr-page'
      fullPath: '/admin/csr-page'
      preLoaderRoute: typeof AdminCsrPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/csr': {
      id: '/admin/csr'
      path: '/csr'
      fullPath: '/admin/csr'
      preLoaderRoute: typeof AdminCsrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/team/$type/$id': {
      id: '/team/$type/$id'
      path: '/$type/$id'
      fullPath: '/team/$type/$id'
      preLoaderRoute: typeof TeamTypeIdRouteImport
      parentRoute: typeof TeamRoute
    }
    '/about/trustee/$slug': {
      id: '/about/trustee/$slug'
      path: '/trustee/$slug'
      fullPath: '/about/trustee/$slug'
      preLoaderRoute: typeof AboutTrusteeSlugRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/advisory/$slug': {
      id: '/about/advisory/$slug'
      path: '/advisory/$slug'
      fullPath: '/about/advisory/$slug'
      preLoaderRoute: typeof AboutAdvisorySlugRouteImport
      parentRoute: typeof AboutRoute
    }
  }
}

interface AboutRouteChildren {
  AboutAdvisorySlugRoute: typeof AboutAdvisorySlugRoute
  AboutTrusteeSlugRoute: typeof AboutTrusteeSlugRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAdvisorySlugRoute: AboutAdvisorySlugRoute,
  AboutTrusteeSlugRoute: AboutTrusteeSlugRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminCsrRoute: typeof AdminCsrRoute
  AdminCsrPageRoute: typeof AdminCsrPageRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHeroCarouselRoute: typeof AdminHeroCarouselRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMilestonesRoute: typeof AdminMilestonesRoute
  AdminNewsBannerRoute: typeof AdminNewsBannerRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminTestimonialsManagerRoute: typeof AdminTestimonialsManagerRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVoicesRoute: typeof AdminVoicesRoute
  AdminVolunteerPageRoute: typeof AdminVolunteerPageRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminWeeklyHighlightsRoute: typeof AdminWeeklyHighlightsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminCsrRoute: AdminCsrRoute,
  AdminCsrPageRoute: AdminCsrPageRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHeroCarouselRoute: AdminHeroCarouselRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMilestonesRoute: AdminMilestonesRoute,
  AdminNewsBannerRoute: AdminNewsBannerRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminTestimonialsManagerRoute: AdminTestimonialsManagerRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVoicesRoute: AdminVoicesRoute,
  AdminVolunteerPageRoute: AdminVolunteerPageRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminWeeklyHighlightsRoute: AdminWeeklyHighlightsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TeamRouteChildren {
  TeamTypeIdRoute: typeof TeamTypeIdRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamTypeIdRoute: TeamTypeIdRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  MilestonesRoute: MilestonesRoute,
  TeamRoute: TeamRouteWithChildren,
  TestimonialsRoute: TestimonialsRoute,
  BlogSlugRoute: BlogSlugRoute,
  GetInvolvedCsrRoute: GetInvolvedCsrRoute,
  GetInvolvedCsrInfoRoute: GetInvolvedCsrInfoRoute,
  GetInvolvedVolunteerRoute: GetInvolvedVolunteerRoute,
  GetInvolvedVolunteerInfoRoute: GetInvolvedVolunteerInfoRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  GetInvolvedIndexRoute: GetInvolvedIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
